spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hzq_base?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848 # 配置nacos服务地址


dubbo:
  application:
    name: base-service
    owner: hengzhaoqing
  protocol:
    name: dubbo
    port: 20881
#  registry:
#    address: zookeeper://localhost:2181
#    check: true
#    group: dubbo-dev
#    simplified: true
#  metadata-report:
#    address: zookeeper://localhost:2181
#    retry-times: 30
#    cycle-report: false
#    group: dubbo-dev
  scan:
    base-packages: com.hzqing.base.provider
  registry:
    address: nacos://localhost:8848
    group: dubbo-dev


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.hzqing.base.provider.dal.entity
