spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/hzq_auth?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
  application:
    name: auth-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 10680

debug: true


dubbo:
  registry:
    address: nacos://localhost:8848
    group: dubbo-dev
  scan:
    base-packages: com.hzqing.auth.service
  application:
    name: auth-servie

logging:
  level:
    root: info
