
dubbo:
  registry:
    address: zookeeper://localhost:2181
    check: true
    group: dubbo-dev
  scan:
    base-packages: com.hzqing.base.rest
  protocol:
    name: dubbo
    port: 29106
  application:
    name: base-rest

server:
  port: 8080

spring:
  application:
    name: base-rest


  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES