
dubbo:
  registry:
    address: zookeeper://localhost:2181
    check: true
    group: dubbo-dev
  scan:
    base-packages: com.hzqing.base.rest
  protocol:
    name: dubbo
    port: 29106
  application:
    name: base-rest