
dubbo:
  registry:
    address: nacos://localhost:8848
    check: true
    group: dubbo-dev
  scan:
    base-packages: com.hzqing.base.rest
  protocol:
    name: dubbo
    port: 29106

server:
  port: 10600


spring:
  application:
    name: base-rest
  jackson:
#    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
debug: true

security:
  oauth2:
    client:
      client-id: hzq-base-service
      client-secret: 59242ea4104092c510d24a0882b9669d
      access-token-uri: http://localhost:10680/oauth/token
      user-authorization-uri: http://localhost:10680/oauth/authorize
    resource:
      token-info-uri: http://localhost:10680/oauth/check_token

logging:
  level:
    root: warn
    com.hzqing.base.rest: debug
