
dubbo:
  registry:
    address: nacos://localhost:8848
    check: true
    group: dubbo-dev
  scan:
    base-packages: com.hzqing.system.rest

server:
  port: 10601

spring:
  application:
    name: system-rest
  jackson:
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
security:
  oauth2:
    client:
      client-id: hzq-cloud-system
      client-secret: www.hzqing.com
      access-token-uri: http://localhost:10680/oauth/token
      user-authorization-uri: http://localhost:10680/oauth/authorize
    resource:
      token-info-uri: http://localhost:10680/oauth/check_token
      user-info-uri: http://localhost:10680/v1/auth/user

logging:
  level:
    root: info
    com.hzqing.system.rest: debug
